version: "3.9"
services:
  auth:
    build: 
      context: ./auth
    depends_on:
      - postgres
    environment:
      PGAPPNAME: conference_app
      PGDATABASE: conference_db
      PGHOST: postgres
      PGPASSWORD: 123456
      PGPORT: 5432
      PGUSER: conference_service
    ports:
      - "8083:80"
    volumes:
      - ./auth/data:/usr/local/auth/data
      - ./auth/src:/usr/local/auth/src
  conference:
    build: 
      context: ./conference
    depends_on:
      - auth
      - locations
      - postgres
    environment:
      AUTH_API_URL: http://auth/api
      PGAPPNAME: conference_app
      PGDATABASE: conference_db
      PGHOST: postgres
      PGPASSWORD: 123456
      PGPORT: 5432
      PGUSER: conference_service
    ports:
      - "8080:80"
    volumes:
      - ./conference/data:/usr/local/conference/data
      - ./conference/src:/usr/local/conference/src
  frontend:
    build:
      context: ./frontend
    depends_on:
      - conference
      - locations
    environment:
      PORT: 80
      REACT_APP_API_URL: http://localhost:8081/api
    ports:
      - "8081:80"
  locations:
    build: 
      context: ./locations
    depends_on:
      - postgres
    environment:
      AUTH_API_URL: http://auth/api
      PGAPPNAME: conference_app
      PGDATABASE: conference_db
      PGHOST: postgres
      PGPASSWORD: 123456
      PGPORT: 5432
      PGUSER: conference_service
    ports:
      - "8082:80"
    volumes:
      - ./locations/data:/usr/local/locations/data
      - ./locations/src:/usr/local/locations/src
  postgres:
    container_name: postgres
    environment:
      POSTGRES_DB: conference_db
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: conference_service
    image: "postgres:latest"
    ports:
      - "5432:5432"
    volumes: 
      - ./conference/data:/data/db
